version: '3.4'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - demo_net
    environment:
      - WDS_SOCKET_PORT=0

  # React Frontend Service
  react:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - demo_net
    environment:
      - WDS_SOCKET_PORT=0

networks:
  demo_net:
    external: true
