# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  monitoringcomservice:
    image: monitoringcomservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5249:5249
    networks:
      - demo_net
    depends_on:
      - db3
    environment:
      - LOCALDB__dbHost=db3
      - LOCALDB__dbPort=3306
      - LOCALDB__dbName=dm_monitoring
      - LOCALDB__dbUser=root
      - LOCALDB__dbPassword=root
      # ... other environment variables ...
      - Jwt__Token=AcrViINqhjkdEM4zOO8f04KdUBEOAzjJ61VfPajoFdDz3WvEctJg
      - Hashids__Salt=kleWoYZ6Z8
      - Serilog:WriteTo:0:Args:path=/logs/log.txt
      - RabbitMQ__Connection=amqps://ejjgjahg:HFXjx2E2jq79wTZau8rOQO41sw1EiYeq@crow.rmq.cloudamqp.com/ejjgjahg

  db3:
    image: mysql:8.0
    ports:
      - 3309:3306
    networks:
      - demo_net
    environment:
      MYSQL_DATABASE: 'dm_monitoring'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  demo_net:
    external: true